version: "3"

services: 
  redis:
    image: redis
    container_name: ganfan_redis
    restart: always
    ports: 
      - 6379:6379
    volumes: 
      - ~/docker/redis/data:/data
    command: -- appendonly yes
    tty: true